Add .env

diff --git a/ssh-ec2 b/ssh-ec2
--- a/ssh-ec2
+++ b/ssh-ec2
@@ -50,6 +50,7 @@
 
 # File
 # - .rsyncignore      : list of directories to ignore when synchronize files with rsync
+# - .env              : Environment variables. Lower priority.
 
 set -e # Detect all errors
 shopt -s extglob
@@ -58,7 +59,7 @@ CREATE_SECURITY_GROUP=no
 # Defautl security group
 AWS_SECURITY_GROUP=SshEC2
 
-# ---------------- For debug ----------------
+# ----------- For debug
 if [[ "${DEBUG}" == y ]]; then
   #AWS_DRY= --dryrun
   #AWS_INSTANCE_TYPE=t2.small
@@ -71,32 +72,54 @@ if [[ "${DEBUG}" == y ]]; then
   #NO_RSYNC_BEGIN=y
   #NO_RSYNC_END=y
 fi
-# ---------------- End For debug ----------------
+# ----------- End For debug
 
+# ----------- Manage colors
+if test -t 1; then
 
+    # see if it supports colors...
+    ncolors=$(tput colors)
 
+    if test -n "$ncolors" && test $ncolors -ge 8; then
+        normal="$(tput sgr0)"
+        red="$(tput setaf 1)"
+        green="$(tput setaf 2)"
+        yellow="$(tput setaf 3)"
+        gray="$(tput setaf 8)"
+    fi
+fi
+
+# ----------- Manage .env
+# Set only undefined variables. .env have lower priority
+# For debug, replace '.' by 'cat'
+. <( grep -v '^#' .env  | while read line; do
+    key=$(echo $line | cut -d '=' -f 1)
+    if [[ ! -z "$key" && -z "${!key}" ]]; then
+        echo $line | sed -r "s/=(.*)/='\1'/"
+    fi
+    done
+    )
+
+# ----------- Check presence of others tools
 if  [[ "$(which aws)" == ""  ]]; then
-    echo "ERROR: Install AWS CLI before use ssh-ec2 (https://tinyurl.com/yd4ru2nu)" >&2
+    echo -e "${red}ERROR${normal}: Install AWS CLI before use ssh-ec2 (https://tinyurl.com/yd4ru2nu)" >&2
     exit 1
 fi
 
 if  [[ "$(which jq)" == ""  ]]; then
-    echo "ERROR: Install jq before use ssh-ec2" >&2
+    echo -e "${red}ERROR${normal}: Install jq before use ssh-ec2" >&2
     exit 1
 fi
 
+# ----------- Defaults values
 _DEFAULT_FINAL_STATE=terminate
 _DEFAULT_REGION=eu-central-1
 _DEFAULT_INSTANCE_TYPE=p2.xlarge
-# FIXME
-_DEFAULT_INSTANCE_TYPE=t2.small
 _DEFAULT_MULTIPLEX=
 _DEFAULT_IMAGE_NAME="Deep Learning AMI (Ubuntu)*"
 _DEFAULT_IAM_INSTANCE_PROFILE="EC2ReadOnlyAccessToS3"
 _DEFAULT_RSYNC_QUIET=--quiet
-#_DEFAULT_USER_DATA="sudo locale-gen $(locale | grep LANG= | cut -d '=' -f 2);"
-_DEFAULT_USER_DATA="#!/bin/bash
-echo 'bar' > /tmp/bar"
+_DEFAULT_USER_DATA="sudo locale-gen $(locale | grep LANG= | cut -d '=' -f 2);"
 _DEFAULT_SECURITY_GROUP=SshEC2
 
 
@@ -104,7 +127,7 @@ nb_of_instance=$(pgrep -fa bash | tr '\n' ' ' | grep -c ssh-ec2 )
 declare -A TAGS # The user can set somme additional tags
 RSYNC_QUIET=${_DEFAULT_RSYNC_QUIET}
 
-# --- Analyse parameters
+# ----------- Analyse parameters
 
 function arg_leave() {
     AWS_FINAL_STATE=leave
@@ -167,12 +190,12 @@ function arg_help() {
         "[--multi <tmux|screen|none>] \\ \n" \
         "[-i <pem file>] [-[LR] port:host:port] [cmds*]"
     echo "Samples:"
-    echo "ssh-ec2 make          # Create, sync, execute, sync and terminate instance"
-    echo "ssh-ec2 --detach make # Create, sync, execute in bg and detach session"
-    echo "ssh-ec2 --attach      # Attach current session"
-    echo "ssh-ec2 --finish      # Attach, rsync and terminate instance EC2"
-    echo "ssh-ec2 --stop make   # Create, sync, execute, sync and save instance EC2"
-    echo "ssh-ec2 --leave       # Create, sync, execute"
+    echo "${green}ssh-ec2 make          ${gray}# Create, sync, execute, sync and terminate instance"
+    echo "${green}ssh-ec2 --detach make ${gray}# Create, sync, execute in bg and detach session"
+    echo "${green}ssh-ec2 --attach      ${gray}# Attach current session"
+    echo "${green}ssh-ec2 --finish      ${gray}# Attach, rsync and terminate instance EC2"
+    echo "${green}ssh-ec2 --stop make   ${gray}# Create, sync, execute, sync and save instance EC2"
+    echo "${green}ssh-ec2 --leave       ${gray}# Create, sync, execute${normal}"
     exit 0
 }
 
@@ -217,7 +240,7 @@ while getopts "$optspec" optchar; do
                     ;;
                 *)
                     if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
-                        echo "Unknown option --${OPTARG}" >&2
+                        echo -e "${red}Unknown option --${OPTARG} ${normal}" >&2
                     fi
                     ;;
             esac;;
@@ -256,7 +279,7 @@ while getopts "$optspec" optchar; do
             ;;
         *)
             if [ "$OPTERR" != 1 ] || [ "${optspec:0:1}" = ":" ]; then
-                echo "Non-option argument: '-${OPTARG}'" >&2
+                echo -e "${red}Non-option argument: '-${OPTARG}'${normal}" >&2
             fi
             ;;
     esac
@@ -363,14 +386,14 @@ if [[ ! -z "${AWS_PEM}" ]]; then
 PEM_SSH="-i ${AWS_PEM}"
 fi
 
-echo "----------------------------------------------------------"
-echo "EC2 Name: ${AWS_NAME_INSTANCE}"
-echo "Region:   ${AWS_REGION}"
-echo "Type:     ${AWS_INSTANCE_TYPE}"
-echo "Image Id: ${AWS_IMAGE_ID} (${AWS_IMAGE_NAME})"
-echo "Key name: ${AWS_KEY_NAME}"
-echo "Tags:     ${__tags}"
-echo "----------------------------------------------------------"
+echo "${green}----------------------------------------------------------${normal}"
+echo "${green}EC2 Name: ${AWS_NAME_INSTANCE}${normal}"
+echo "${green}Region:   ${AWS_REGION}${normal}"
+echo "${green}Type:     ${AWS_INSTANCE_TYPE}${normal}"
+echo "${green}Image Id: ${AWS_IMAGE_ID} (${AWS_IMAGE_NAME})${normal}"
+echo "${green}Key name: ${AWS_KEY_NAME}${normal}"
+echo "${green}Tags:     ${__tags}${normal}"
+echo "${green}----------------------------------------------------------${normal}"
 
 trap_with_arg() {
     func="$1" ; shift
@@ -380,7 +403,7 @@ trap_with_arg() {
 }
 
 function abort() {
-    echo -e "\n\e[91mAbort\e[0m"
+    echo -e "\n${red}Abort${normal}"
     exit -1
 }
 
@@ -398,7 +421,7 @@ function finish() {
         # Stop the instance
         case "${AWS_FINAL_STATE}" in
             stop)
-              echo -e "\e[33mStop instance...\e[0m \c"
+              echo -e "${red}Stop instance...${normal} \c"
               aws --region ${AWS_REGION} ec2 stop-instances --instance-ids ${AWS_INSTANCE_ID} ${AWS_DRY} --output text ${AWS_DRY} > /dev/null
               if [[ -z "${AWS_DRY}" ]]; then
                   while STATE=$(aws --region ${AWS_REGION} ec2 describe-instances \
@@ -408,11 +431,11 @@ function finish() {
                     test "$STATE" != "stopped" -a "$STATE" != "terminated"; do
                     sleep 3;
                   done;
-                  echo -e "\e[33mdone\e[0m"
+                  echo -e "${red}done${normal}"
               fi
               ;;
             terminate)
-                echo -e "\e[32mTerminate instance... \e[0m\c"
+                echo -e "${yellow}Terminate instance... ${normal}\c"
                 aws --region ${AWS_REGION} ec2 terminate-instances --instance-ids ${AWS_INSTANCE_ID} ${AWS_DRY} --output text ${AWS_DRY} > /dev/null
                 while STATE=$(aws --region ${AWS_REGION} ec2 describe-instances \
                     --instance-ids $AWS_INSTANCE_ID \
@@ -422,17 +445,17 @@ function finish() {
                   sleep 3;
                 done;
                 if [[ "$CREATE_SECURITY_GROUP" == "yes" ]] ; then
-                    echo -e "\e[32mand security group... \e[0m\c"
+                    echo -e "${yellow}and security group... ${normal}\c"
                     aws --region ${AWS_REGION} ec2 delete-security-group --group-name ${AWS_NAME_INSTANCE}
                  fi
-                echo -e "\e[32mdone\e[0m"
+                echo -e "${red}done${normal}"
                 ;;
             *)
                 if [[ $nb_of_instance > 1 ]] ; then
                     AWS_FINAL_STATE=leave
-                    echo -e "\e[91mWARNING: Another connexion to EC2 instance is alive. The AWS EC instance is active\e[0m"
+                    echo -e "${yellow}WARNING: Another connexion to EC2 instance is alive. The AWS EC instance is active${normal}"
                 else
-                    echo -e "\e[91mWARNING: The AWS EC instance ${AWS_NAME_INSTANCE} is alive\e[0m" >&2
+                    echo -e "${yellow}WARNING: The AWS EC instance ${AWS_NAME_INSTANCE} is alive${normal}" >&2
                 fi
                 ;;
         esac
@@ -554,7 +577,7 @@ if [[ "$nb_of_instance" < 2 && -z "${NO_RSYNC_BEGIN}" ]] ; then
       ${RSYNC_QUIET} \
       --copy-links
 else
-    echo -e "\e[33mWarning: No rsync (other ssh-ec2 session ?)\e[0m"
+    echo -e "${yellow}Warning: No rsync (other ssh-ec2 session ?)${normal}"
 fi
 
 _CD="[[ -e \"${AWS_RSYNC_DIR}\" ]] && cd \"${AWS_RSYNC_DIR}\""
@@ -593,7 +616,7 @@ case "${MULTIPLEX}" in
         ;;
       *)
         if [[ "$SSH_DETACH" == y ]]; then
-            echo "ERROR: Impossible to detach session without MULTIPLEX" >&2
+            echo "${red}ERROR${normal}: Impossible to detach session without MULTIPLEX" >&2
             exit 1
         else
           _TERM=-t
@@ -629,6 +652,6 @@ if [[ "$nb_of_instance" < 2 && -z "${NO_RSYNC_END}" ]] ; then
       --ignore-times
     echo -e "done"
 else
-    echo -e "\e[33mWarning: No rsync\e[0m"
+    echo -e "${yellow}Warning: No rsync${normal}"
 fi
 exit 0
